apiVersion: apps/v1
kind: Deployment
metadata:
  name: kakaoTalk
  labels:
    app: kakaoTalk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kakaoTalk
  template:
    metadata:
      labels:
        app: kakaoTalk
    spec:
      containers:
        - name: kakaoTalk
          image: username/kakaoTalk:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5